# Utilise une image Python légère
FROM python:3.13-slim

# Définit le dossier de travail dans le conteneur
WORKDIR /app

# Copie le fichier des dépendances et les installe
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copie tout le reste de ton code Python
COPY . .

# La commande pour lancer ton script principal
CMD ["python", "main.py"]