version: '3.8'

services:
  etl:
    build: .
    container_name: healthai_etl
    # Permet au conteneur de trouver la BDD de Laravel sur ta machine
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana-enterprise
    container_name: healthai_grafana
    ports:
      - "3000:3000"
    environment:
      # Mot de passe par défaut pour te connecter à l'interface
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    extra_hosts:
      - "host.docker.internal:host-gateway"