# Utilise une image Python légère
FROM python:3.12-slim

# Définit le dossier de travail dans le conteneur
WORKDIR /app

# Installe les dépendances système nécessaires pour psycopg2 et python-magic
RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		build-essential \
		libpq-dev \
		libmagic1 \
	&& rm -rf /var/lib/apt/lists/*

# Copie le fichier des dépendances et les installe
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copie tout le reste de ton code Python
COPY . .

# La commande pour lancer ton script principal
CMD ["python", "main.py"]